import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Menu from './globalComponents/Menu';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="flex flex-col-reverse">
      <Menu />
      <body className={inter.className}>{children}</body>
    </html>
  );
}